
ALTER TABLE USERINFO
ADD PHONE VARCHAR(10);

UPDATE USERINFO
SET PHONE='8476472831'
WHERE USERID=101;

USE MphasisFoodDelDb;
SELECT * FROM USERINFO;
SELECT * FROM LOCATION
SELECT * FROM RESTAURANT

UPDATE USERINFO
SET USERROLE='ROLE'
WHERE USERID=103


INSERT INTO RESTAURANT
VALUES(201,'A2B',2,102,200),(202,'VASANTH BHAVAN',1,102,300);


INSERT INTO MENUITEM
VALUES(302,'Masala Dosa',201,120)

INSERT INTO MENUITEM
VALUES(303,'CHK65',201,350,'NON-VEG')


UPDATE MENUITEM
SET DISHTYPE='VEG' 
WHERE DISHTYPE IS NULL


INSERT INTO [ORDER]
VALUES(402,103,201,550)


INSERT INTO ORDERLINEITEMS
VALUES(502,401,302,3)

SELECT * FROM RESTAURANT
SELECT * FROM MENUITEM
SELECT * FROM ORDE



--UPDATE USERINFO
--SET LocationId=5
--WHERE LocationName='Mumbai'


--DELETE FROM location
--WHERE LOCATIONID=5


SELECT TOP 2 LOCATIONNAME FROM LOCATION

SELECT MINORDERVALUE FROM RESTAURANT 

SELECT USERNAME ,ISNULL(PHONE,'NA') USERPHONE FROM USERINFO
SELECT CONCAT(USERNAME ,':' ,ISNULL(PHONE,'NA')) DISPLAYTEXT FROM USERINFO


SELECT COUNT(*),USERLOCATION FROM USERINFO
GROUP BY USERLOCATION
HAVING COUNT(*)>=2







INSERT INTO LOCATION VALUES(3,'BANGALORE'),(5,'DELHI'),(2,'CHENNAI');


--Get users list from given location ID
SELECT UI. * ,loc.LocationName FROM USERINFO UI
inner join [Location] LOC ON UI.USERLOCATION=LOC.LocationId
WHERE UI.USERLOCATION=1

--Get line items with Dishname and Quantity
SELECT QTY ,DISHNAME FROM ORDERLINEITEMS
INNER JOIN MenuItem ON ORDERLINEITEMS.MENUID=MenuItem.MID
WHERE ORDERID=401


--Get Average Price of Items For a Given Restaurant
SELECT AVG(PRICE) FROM MenuItem 
WHERE RESTAURANTID=201

--Get Average Price of Items of A2B-SubQuery
SELECT FLOOR(AVG(PRICE)) FROM MenuItem
WHERE RESTAURANTID=(SELECT RID FROM Restaurant WHERE RNAME='A2B')


--Get restaurants With Menu 1 Order
SELECT * FROM Restaurant
WHERE RID IN (SELECT DISTINCT(RESTID) FROM [ORDER])

--Get restaurants WithOUT  Order
SELECT * FROM Restaurant
WHERE RID IN (SELECT DISTINCT(RESTID) FROM [ORDER])


--Get Restaurants Without ORDER Using JOINS
SELECT * FROM Restaurant R
LEFT JOIN [ORDER] O ON R.RID=O.RESTID
WHERE O.RESTID IS NULL

SELECT RESTID,COUNT(*) FROM [Order]
GROUP BY RESTID
ORDER BY COUNT(*) DESC

SELECT * FROM Location;

SELECT * FROM [Order]

SELECT * FROM ORDERLINEITEMS;
INSERT INTO ORDERLINEITEMS VALUES(501,402,303,3);

SELECT * FROM USERINFO;
SELECT * FROM MenuItem;
SELECT * FROM Restaurant;


SELECT * FROM MenuItem M1
WHERE M1.PRICE>
(SELECT AVG(M2.PRICE)
FROM MenuItem M2 GROUP BY M2.RESTAURANTID
HAVING M1.RESTAURANTID=M2.RESTAURANTID
)

--Get VEG ONLY RESTAURANTS
--SUBQUERY CORROLETED SUBQUERY
SELECT * FROM Restaurant R1
WHERE NOT EXISTS (SELECT * FROM MenuItem M1
WHERE M1.RESTAURANTID=R1.RID AND DISHTYPE='NON-VEG')


SELECT * FROM Visitor
WHERE RID NOT IN (SELECT DISTINCT(RESTAURANTID)
FROM MenuItem WHERE DISHTYPE='NON-VEG')

USE VisitorManagement;
 SELECT * FROM Location;
 INSERT INTO Location VALUES(4,'chennai'),(5,'Hyderabad'),(6,'bangalore'),(7,'Paris'),(8,'Pune'),(9,'Punjab'),(10,'Noida');



 SELECT * FROM Host;
  INSERT INTO Host VALUES
  (10,'Venkat',001,'IT',1),
  (20,'Sai',002,'NON-IT',2),
  (30,'Sukumar',003,'IT',3),
  (40,'Vamsi',004,'HR',10),
  (50,'Varun',005,'FINANCE',4),
  (60,'Kaushik',006,'FINANCE',6),
  (70,'raidu',007,'SUPPORT',5),
  (80,'Nanda',008,'HR',7),
  (90,'Aditya',009,'IT',8),
  (100,'Shakti',010,'IT',9);

   SELECT * FROM Visitor;

    INSERT INTO Visitor VALUES
	(101,'Stark',2,'Grok','Meeting',4561,21-4-24,10),
	(102,'Thor',3,'Idp','Training',3333,26-5-24,20),
	(103,'Strange',5,'Barclay','Technical',111,14-6-24,30),
	(104,'Hulk',6,'Boeing','Training',2222,05-7-24,40),
	(105,'Vanda',7,'Foodhub','Audit',5555,05-9-24,50),
	(106,'Panther',9,'Mphasis','Interview',6666,13-9-24,60),
	(107,'Thala',10,'Accenture','Audit',7777,21-7-24,70),
	(108,'Thalapathy',1,'Codeiox','ProjectPlan',8888,21-4-24,80),
	(109,'Vijay',5,'Mitsogo','Interview',9999,22-5-24,90),
	(110,'Sanjoy',6,'CorroHealth','Discussion',4444,20-5-24,100);

