--2.
--SELECT * FROM LOCATION

--3.
--SELECT VI.VNAME,LocationName FROM VISITOR VI
--INNER JOIN LOCATION L ON L.LocationId = VI.LID

--4.
--SELECT * FROM LOCATION
--WHERE LocationName LIKE 'H%'

--5.
--SELECT COUNT(*) FROM Host

--6.
--SELECT COUNT(*) FROM Host 
--WHERE LOCATIONID = 1

--7.
--SELECT * FROM VISITOR
--WHERE HostId = 1002

--8.
--SELECT * FROM VISITOR
--WHERE Date_='2/05/2026'

--9.
--SELECT * FROM VISITOR

--ORDER BY Date_

--10.
--SELECT * FROM VISITOR
--WHERE HostId IS NULL

--11.
--SELECT VISITOR.*,HName FROM VISITOR
--INNER JOIN Host H ON H.HID = VISITOR.HostId
--WHERE H.HName = 'SONA'

--12.
--SELECT V.*,H.HName FROM VISITOR V
--INNER JOIN Host H ON H.HID = V.HostId
--WHERE H.DEPARTMENT = 'BANKING'

--13.
--SELECT COUNT(VisitorID),Date_ FROM VISITOR 
--GROUP BY HostId, Date_
--WHERE H.HID = 1002 AND V.Date_ = '25/05/2025'

--14.
--SELECT COUNT(*) FROM VISITOR
--WHERE LID = 1 OR Date_='25/05/2025' 

--15.
--SELECT * FROM VISITOR
--WHERE HostId = (SELECT TOP 1 HostId FROM VISITOR 
--GROUP BY HostId
--ORDER BY COUNT(*) DESC )

--16.
--SELECT * FROM VISITOR
--WHERE HostId = (SELECT TOP 1 HostId FROM VISITOR 
--GROUP BY HostId
--ORDER BY COUNT(*) ASC )
--SELECT H.* FROM Host H 
--JOIN (SELECT HostId, COUNT(*) FROM VISITOR
--GROUP BY HostId ORDER BY COUNT(*) DESC ) AS V ON H.HID = V.HostId

--17.
--SELECT *
--FROM Host
--WHERE HID NOT IN (SELECT DISTINCT HostId FROM VISITOR WHERE HostId IS NOT NULL);

--18.
SELECT Date_, COUNT(*) AS VISITOR
FROM visitor
GROUP BY Date_
ORDER BY Date_;

--19.
 
SELECT *
FROM VISITOR
WHERE HostId = 1 AND Date_ BETWEEN '2/05/2025' AND '25/05/2025';  

--20.
SELECT *
FROM Host
WHERE DEPARTMENT != 'Manager';

--21
SELECT *
FROM VISITOR
INNER JOIN Mobile M ON M.VisitorID = VISITOR.VisitorID
WHERE M.MobileNumber IS NOT NULL