--CREATE TABLE Location(
--LocationId bigint NOT NULL PRIMARY KEY,
--LocationName nvarchar(20)
--)

--ALTER table Location ADD Constraint
--LOC_NAME_UNIQUE UNIQUE(LocationName)

--CREATE TABLE USERINFO(
--USERID BIGINT NOT NULL PRIMARY KEY,
--USERNAME NVARCHAR(30) NOT NULL,
--USERROLE NVARCHAR(10) NOT NULL,
--EMAIL NVARCHAR(100) NOT NULL,
--USERPASSWORD NVARCHAR(10) NOT NULL,
--USERLOCATION BIGINT NOT NULL
--)
--ALTER TABLE USERINFO ADD CONSTRAINT 
--USERINFO_LOCATION_FK FOREIGN KEY(USERLOCATION) 
--REFERENCES LOCATION(LocationId)

--ALTER TABLE USERINFO ADD CONSTRAINT 
--USERINFO_CHECK CHECK(USERROLE IN ('ADMIN','OWNER','USER'))

--CREATE TABLE Restaurant(
--RID BIGINT NOT NULL PRIMARY KEY,
--RNAME NVARCHAR(30) NOT NULL,
--RLOCATION BIGINT NOT NULL,
--ROWNER BIGINT NOT NULL,
--MINORDERVALUE INT DEFAULT 100
--)

--ALTER TABLE Restaurant ADD CONSTRAINT
--Restaurant_RNAME_UNIQUE UNIQUE(RNAME,RLOCATION)

--ALTER TABLE Restaurant ADD CONSTRAINT
--Restaurant_USERINFO_FK FOREIGN KEY(ROWNER)
--REFERENCES USERINFO(USERID)

--CREATE TABLE MenuItem(
--MID BIGINT NOT NULL PRIMARY KEY,
--DISHNAME NVARCHAR(50) NOT NULL,
--RESTAURANTID BIGINT NOT NULL,
--PRICE DECIMAL(8,2)
--)

--ALTER TABLE MenuItem
--ADD CONSTRAINT MenuItem_DISHNAME UNIQUE(DISHNAME,RESTAURANTID)
