--CREATE DATABASE VISITORDB
USE  VISITORDB;
 CREATE TABLE VISITOR(
 VID  BIGINT PRIMARY KEY ,
 VNAME NVARCHAR(20)  NOT NULL,
 LId   BIGINT NOT NULL FOREIGN KEY REFERENCES LOCATION(LId),
 PCOMPANY NVARCHAR(29) NOT NULL,
 PURPOSE  NVARCHAR(22) NOT NULL,
 VDATE  NVARCHAR NOT NULL,
 HId BIGINT NOT NULL FOREIGN KEY REFERENCES HOST(HId)
 )
  
  CREATE TABLE HOST(
 HID  BIGINT PRIMARY KEY ,
 HNAME NVARCHAR(20)  NOT NULL,
 EMPNO NVARCHAR(20) NOT NULL,
 DEPT NVARCHAR(20) NOT NULL,
 LId BIGINT NOT NULL FOREIGN KEY REFERENCES LOCATION(LId)
 )
  
  CREATE TABLE LOCATION(
  LId BIGINT PRIMARY KEY ,
  LOCNAME NVARCHAR(20)  NOT NULL
  )
  CREATE TABLE MOBILENUMBER(
  MId BIGINT PRIMARY KEY ,
  MNO NVARCHAR(20)  NOT NULL,
  VID BIGINT NOT NULL FOREIGN KEY REFERENCES VISITOR(VID)
  )
 
  INSERT INTO VISITOR
  VALUES (12,'VAMSHI',2,'C2C','BUSINESS',2,102)
 
  SELECT VNAME,PCOMPANY FROM VISITOR